language: node_js
node_js:
  - "6"
  - "7"
  - "8"

os:
  - linux
  - osx

before_install:
  - npm install nsp -g

script:
  - npm test
  - npm run lint
  - npm run nsp

jobs:
  include:
    - stage: docs
      node_js: "6"
      script: ./deploy_documentation.sh
      skip_cleanup: true
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      on:
        branch: master
