notifications:
  email:
    on_success: never
    on_failure: change

language: node_js
node_js:
  - "8"
#  - "10"

os:
  - linux
  - osx

script:
  - yarn test
  - yarn run lint

jobs:
  include:
    - stage: docs
      node_js: "8"
      script: chmod +x ./tool/documentation_create.sh && chmod +x ./tool/documentation_deploy.sh && source ./tool/documentation_deploy.sh
      skip_cleanup: true
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      on:
        branch: master
    - stage: "Create GitHub Tag and Publish Package"
      if: branch = master AND tag is blank AND fork is false AND repo = head_repo AND type != pull_request
      node_js: "8"
      os: linux
      sudo: false
      dist: trusty
      script: export main_repo="inexorgame/inexor-flex" && chmod +x ./tool/travis_create_tag.sh && source ./tool/travis_create_tag.sh && chmod +x ./tool/travis_publish_npm.sh && source ./tool/travis_publish_npm.sh
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      branches:
        only:
          - master


deploy:
  skip_cleanup: true
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file: inexor-flex-*.tgz
  overwrite: true
  on:
    condition: "$DEPLOY_TO_GITHUB = true"
    repo: inexorgame/inexor-flex
