notifications:
  email:
    on_success: never
    on_failure: change

language: node_js
node_js:
  #- "6"
  - "8"
  #- "9"

os:
  - linux
  # - osx

script:
  - npm test
  - npm run lint

jobs:
  include:
    - stage: docs
      node_js: "8"
      script: chmod +x ./tool/deploy_documentation.sh && ./tool/deploy_documentation.sh
      skip_cleanup: true
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      on:
        branch: master
    - stage: "Create GitHub Tag or Publish to npm"
      if: branch = master AND tag is blank AND fork is false AND repo = head_repo AND type != pull_request
      node_js: "8"
      os: linux
      sudo: false
      dist: trusty
      script: chmod +x ./tool/travis_create_tag.sh && ./tool/travis_create_tag.sh
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      branches:
        only:
          - master
