# Please configure your servers and clients here

[instances]

[instances.31414]
type = "server"
name = "Default production server"
description = "Badly Configurated Servers Inc. proudly presents your first Inexor Server"
# The semantic release range string to select a release.
versionRange = "0.x"
# The release channel or empty to accept all
channelSearch = "*"
autostart = true
autoconnect = true
autorestart = true
