# Please configure your servers and clients here

[instances]

[instances.31414]
type = "server"
name = "Default production server"
description = "Badly Configurated Servers Inc. proudly presents your first Inexor Server"
versionrange = "*"
channel = ""
autostart = true
autoconnect = true
autorestart = true
enet_port = 31415
