# Please configure your servers and clients here

[instances]

[instances.31414]
type = "server"
name = "Default production server"
description = "Badly Configurated Servers Inc. proudly presents your first Inexor Server"
# The semantic release range string to select a release.
versionRange = "0.x"
# The release channel or empty to accept all
channelSearch = "*"
autostart = false
autoconnect = false
autorestart = false

[instances.31417]
type = "client"
name = "Default production client"
description = "Badly Configurated Clients Inc. proudly presents your first Inexor Client"
# The semantic release range string to select a release.
versionRange = "0.x"
# The release channel or empty to accept all
channelSearch = "*"
autostart = false
autoconnect = false
autorestart = false
