# Please configure your servers and clients here

[instances]

[instances.31414]
type = "server"
name = "Default production server"
description = "Badly Configurated Servers Inc. proudly presents your first Inexor Server"
versionRange = "0.x"
channelSearch = "*"
autostart = true
autoconnect = true
autorestart = false

[instances.31417]
type = "client"
name = "Default production client"
description = "Badly Configurated Clients Inc. proudly presents your first Inexor Client"
versionRange = "0.x"
channelSearch = "*"
autostart = true
autoconnect = true
autorestart = false
